### ISSUE TITLE
Horizontal scroll behavior broken in Chrome Device Toolbar

### ISSUE THREAD

**Issue by mherodev** [loktar00/react-lazy-load#105]
For whatever reason, when horizontal scrolling through an overflow container in Chrome's Device Toolbar, the lazy loading behavior is broken.

I have an album with an example of correct and erroneous behavior, here:

http://imgur.com/a/tIuat

**Comment by hamza-jutt** [comment]
I've got a  horizontal scrolling through an overflow container and every image loads at once there in no lazy loading. is there some specific config for that?

**Comment by loktar00** [comment]
Works with 4.0 now, I added an example due to this issue and made sure it worked :) fixed with #155
