### ISSUE TITLE
Is there a way to force the library to trigger lazyLoadHandler?

### ISSUE THREAD

**Issue by mherodev** [loktar00/react-lazy-load#106]
For edge-cases that aren't handled by resize and scroll?

**Comment by ShahSoft** [comment]
Fixed this for myself by adding custom event to window.

In lazyLoad.js:
> `window.customLazyEvent = new Event('updateLazy');`
>   `(0, _eventlistener.add)(window, 'updateLazy', this.lazyLoadHandler);`

and trigger anywhere as needed:
> `window.dispatchEvent(window.customLazyEvent);`

**Comment by profimediacz** [comment]
Hi Loktar00,

could you add some util method, which can be called, when we want to force recalculate visibililty of images?

Something like:
`
const lazyCheckEventName = "customUpdateLazyCheck";
export const dispatchLazyCheckEvent = () => {
    let customLazyEvent = new CustomEvent(lazyCheckEventName, {bubbles: true,cancelable: true});
    window.dispatchEvent(customLazyEvent);
};
`

And in the LazyLoad then capture this event?

Best

**Comment by NNSTH** [comment]
To anyone who needs a quick W/A for this issue, I found the way of triggerring "resize" event on window, as shown [here](https://stackoverflow.com/a/1818513/9792842):
modern browsers:
window.dispatchEvent(new Event('resize'));

old browsers (include IE):
var resizeEvent = window.document.createEvent('UIEvents'); 
resizeEvent.initUIEvent('resize', true, false, window, 0); 
window.dispatchEvent(resizeEvent);

**Comment by loktar00** [comment]
This should be resolved now in 4.0 due to switching to using `IntersectionObserver`. Going to close since I'm 99% sure it should be good, but feel free to reopen if not.
