### ISSUE TITLE
how can i make it work with display:flex?

### ISSUE THREAD

**Issue by bitwikinger** [loktar00/react-lazy-load#112]
Hey,

i have some issues with lazy loading within a display:flex container.

Here is the modified example code:

index.jsx
`import React, { Component } from 'react';
import LazyLoad from 'react-lazy-load';

import './style.css'

class Application extends Component {
  render() {
    return (
      <div style={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
        <div>{'sdf'}</div>
        <div style={{ display: 'flex', flex: 1, flexDirection: 'column', margin: '20px 0', overflow: 'auto' }}>
          Scroll to load images.
          <div className="filler" />
          <LazyLoad height={762} offsetVertical={300}>
            <img src='http://apod.nasa.gov/apod/image/1502/HDR_MVMQ20Feb2015ouellet1024.jpg' />
          </LazyLoad>
          <div className="filler" />
          <LazyLoad height={683} offsetVertical={20}>
            <img src='http://apod.nasa.gov/apod/image/1502/2015_02_20_conj_bourque1024.jpg' />
          </LazyLoad>
          <div className="filler" />
          <div className="ScrollableContainer">
            <div className="filler" />
            <div className="filler" />
            <div className="filler" />
            <LazyLoad height={480}>
              <img src='http://apod.nasa.gov/apod/image/1502/MarsPlume_jaeschke_480.gif' />
            </LazyLoad>
          </div>
          <div className="filler" />
          <LazyLoad height={720} offsetVertical={20}>
            <img src='http://apod.nasa.gov/apod/image/1502/ToadSky_Lane_1080_annotated.jpg' />
          </LazyLoad>
          <div className="filler" />
        </div>
        <div>{'sdf'}</div>
      </div>
    );
  }
}

export default Application;
`

template.ejs:
`<!DOCTYPE html>
<html style="height: 100%">
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
    <meta charset="utf-8" />
    <title>React Lazy Load basic example</title>
  </head>

  <body style="height: 100%; margin: 0">
    <div id="content" style="height: 100%;"></div>
    <script type="text/javascript" src="<%- webpackAsset('vendor', 'js') %>"></script>
    <script type="text/javascript" src="<%- webpackAsset('bundle', 'js') %>"></script>
  </body>
</html>
`

Does anyone have some experience with this?
Thanks in advance.

PS: how can i make the code look like code? :)

**Comment by cs-manughian** [comment]
The way I did it is that I had a container div with the wrapped lazy loaded components inside. This container has the flex css (`display: flex`, etc.). Then I overwrote the display css for the .LazyLoad class to `display: inline-block` (instead of `display: block` for divs). My components wrapped in the LazyLoad component have the flex styling `flex: 1`. Let me know if that helps!

**Comment by loktar00** [comment]
This should now work properly since I switched over to `IntersectionObserver`. The example includes a flex example with horizonta loading.
