### ISSUE TITLE
Calling PropTypes validators directly is not supported by the `prop-types`

### ISSUE THREAD

**Issue by FedericoCapaldo** [loktar00/react-lazy-load#114]
`Warning: Failed propType: Calling PropTypes validators directly is not supported by the 'prop-types' package`

I believe this issue has already been resolved by @gaearon for the prop-types module in the version 15.5.10.  [See same problem here](https://github.com/malte-wessel/react-custom-scrollbars/issues/153)

If I am not mistaken, that the error in my app is given by the previous version referenced in your repo. is it possible to update it [like so](https://github.com/malte-wessel/react-custom-scrollbars/commit/ec4fb86f9f80dc05f0ccc1e1402bedd07a3d3b49#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) please?

**Comment by loktar00** [comment]
Upgrading the library to TS, and this issue is crazy old so not relevant anyway regardless I guess.
