### ISSUE TITLE
Wrapped Images with Lazy Load Not Working Anymore After Upgrading to React 16

### ISSUE THREAD

**Issue by dschinkel** [loktar00/react-lazy-load#116]
We upgraded our project to the following:

```
"react": "^16.2.0",
"react-dom": "^16.2.0",
"prop-types": "^15.6.0",
"react-lazy-load": "^3.0.13"

```
It breaks our entire site because almost every image on our site is wrapped with react-lazy-load.  **Works just fine in React 15**.  This is a site which receives millions of hits so if we can't get this working in React 16 then we're stuck.  When we remove `<LadyLoad />` below, the image comes through just fine.  But we need to resolve this, so we can finish our React 16 upgrade.

We've run the code below for over a year now.  But that was via React 15.

Now, after upgrading, every image in our site is broken, because wrapped with it:
```
<div>
    <LazyLoad debounce={false} throttle={350}>
       <img className={theme.image} src={image} alt={name} />
    </LazyLoad>
    <TilePlayButton {...{ theme, playButton }} />
    <TileBadge {...{ theme, badge }} />
    <TileNetworkIcon {...{ theme, networkIcon }} />
</div>
```
  
Here is the error we get:

```
invariant.js:42 Uncaught (in promise) Error: Unable to find node on an unmounted component.
    at invariant (invariant.js:42)
    at findDOMNode (react-dom.development.js:15280)
    at LazyLoad.getEventNode (LazyLoad.js:107)
    at LazyLoad.componentDidMount (LazyLoad.js:71)
    at t.notifyAll (vendor.bundle.js:25)
    at r.close (vendor.bundle.js:37)
    at r.closeAll (vendor.bundle.js:6)
    at r.perform (vendor.bundle.js:6)
    at o.perform (vendor.bundle.js:6)
    at o.perform (vendor.bundle.js:6)

```

Shows it's on line 107 in the lazy load source which is here:

```
  }, {
    key: 'getEventNode',
    value: function getEventNode() {
      return (0, _parentScroll2.default)((0, _reactDom.findDOMNode)(this));
    }
  }, {

```
Screenshots here show that it does not work

<img width="500" alt="screen shot 2018-01-07 at 5 48 43 pm" src="https://user-images.githubusercontent.com/338798/34655708-c7160efe-f3d3-11e7-8702-d029f96b7260.png">

<img width="500" alt="screen shot 2018-01-07 at 5 51 01 pm" src="https://user-images.githubusercontent.com/338798/34655714-e395d7a8-f3d3-11e7-9c27-f40f419cfca3.png">
<img width="828" alt="screen shot 2018-01-07 at 6 16 59 pm" src="https://user-images.githubusercontent.com/338798/34655903-1c56b636-f3d7-11e7-9b9e-68c3b2a1ac57.png">

<img width="774" alt="screen shot 2018-01-07 at 6 02 52 pm" src="https://user-images.githubusercontent.com/338798/34655819-cfa690f0-f3d5-11e7-9dd0-6792551eb98a.png">

<img width="686" alt="screen shot 2018-01-07 at 6 11 50 pm" src="https://user-images.githubusercontent.com/338798/34655843-4a1c4834-f3d6-11e7-8938-39fc254ac615.png">

<img width="954" alt="screen shot 2018-01-07 at 6 07 22 pm" src="https://user-images.githubusercontent.com/338798/34655810-a92191f0-f3d5-11e7-9bd2-7854e4c222ce.png">

this is a site that gets hundreds of millions of hits so it's important to try to get it resolved.  I can't figure out in the lazy code what the problem is, I've looked at it a bit.

**Comment by dschinkel** [comment]
if I don't get a response I'm ditching this, tweeting about the fact that this does not work in React 16 and moving onto someone else's carouse.

**Comment by dschinkel** [comment]
can I get a response on this?  Most of our site uses this because we have a lot of images on our site and in React 16 it's not rendering those images.  The same code works just fine in React 15.

**Comment by loktar00** [comment]
Alright going to look into this sometime today actually. Received your email as well.

**Comment by dschinkel** [comment]
The problem was that we had a web project using React v15 and then we import a shared React project of ours that the web also uses. Well that shared project was the project I upgraded from React v15 to v16. But you can't run 2 versions of react in the same project so that was causing the Unable to find node on an unmounted component error. I think your component is probably fine, we're upgrading our web project to 16 and I'll report back.

**Comment by dschinkel** [comment]
thanks again for responding @loktar00
