### ISSUE TITLE
 Cannot find module ''babel-core/register''

### ISSUE THREAD

**Issue by himanshu-9419** [loktar00/react-lazy-load#118]
> node -r 'babel-core/register' ./initializers/server/index.js

module.js:529
    throw err;
    ^

Error: Cannot find module ''babel-core/register''
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at Function.Module._preloadModules (module.js:725:12)
    at preloadModules (bootstrap_node.js:489:38)
    at startup (bootstrap_node.js:198:9)
    at bootstrap_node.js:626:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-lazy-load-basic-example@0.0.0 start: `node -r 'babel-core/register' ./initializers/server/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-lazy-load-basic-example@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HimanshuArora\AppData\Roaming\npm-cache\_logs\2018-02-13T16_50_45_338Z-debug.log

**Comment by loktar00** [comment]
Babel's been removed in the newest branch I'm working on, closing this.
