### ISSUE TITLE
Any possible way to have auto height?

### ISSUE THREAD

**Issue by Drecula** [loktar00/react-lazy-load#120]
Hi,

This is an extremely cool component...thanks!

I have a series of containers that contain arbitrary numbers of components as children. Therefore, I can't know the required height ahead of time. Also, I have display: flex & flex-wrap: wrap, so if the
container is made smaller on the x axis, my children overflow the container since <LazyLoad> isn't flex aware.

Do you think there are ways to address these issues, or is this outside the scope of your design?

Thanks!!!

**Comment by ri8ika** [comment]
Don't set height props. The content will appear in auto height.
