### ISSUE TITLE
Change debounce default value

### ISSUE THREAD

**Issue by crisu83** [loktar00/react-lazy-load#121]
We use this library in our application which is available both on the web as well as on the mobile (as an app that is wrapped with Cordova).

Recently we stumbled on a nasty issue on mobile devices, which first seemed like a bug related to loading of images. It turned out that the issue was caused by the debounce feature in this library, which prevents images from being loaded while scrolling.

I would classify the debounce feature as a performance optimization and I don’t see any reason to perform any optimizations by default. Premature optimizations are usually considered bad practice as they may introduce unwanted side-effects.

That said I would like to suggest that this feature is turned off by default.

Thoughts?

**Comment by OndeVai** [comment]
Agreed. I was stumped for a while on this one, since even cached images were delayed from rendering.

**Comment by loktar00** [comment]
Valid and noted, turning off in the newest version.
