### ISSUE TITLE
Wrap image with <span> instead of <div>

### ISSUE THREAD

**Issue by mario-iliev** [loktar00/react-lazy-load#125]
I'm parsing content from REST API and images are placed in paragraphs.
Since Div in Paragraph is invalid and React is logging "Warning: validateDOMNesting(...): < div > cannot appear as a descendant of < p >."
Personally I would prefer to use < img > with transparent base64 src until it's loaded, and don't use any extra wrappers.

**Comment by waiwaiku** [comment]
Try to use "elementType" props, eg:
```
import {LazyLoad} from 'react-lazy-load';
<LazyLoad elementType="span">
    <img src"/path" />
</LazyLoad>
```
