### ISSUE TITLE
Does this lib work well for SEO purposes?

### ISSUE THREAD

**Issue by ArthurHwang** [loktar00/react-lazy-load#134]
I am just curious if when using this library, does it effect SEO at all?

Mainly, I want to lazy load images in using gatsbyjs and this library.  Will there be any penalty to doing so?

**Comment by tcope25** [comment]
@ArthurHwang use `gatsby-image`

**Comment by loktar00** [comment]
I agree with gatsby might as well use `gatsby-image` Not sure what this would really affect in regards to SEO however, your alt tags wouldn't get crawled in a non js enabled crawler, only thing I can really think of off the top of my head that could potentially affect SEO in any way.
