### ISSUE TITLE
in react @16.9.0 Warning:componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

### ISSUE THREAD

**Issue by chenshufang2015** [loktar00/react-lazy-load#135]
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

**Comment by reintroducing** [comment]
Also just ran into this after updating, would love to hear if there are plans to update this library as it doesn't seem like its been touched for a long time.

**Comment by hieusmiths** [comment]
I think we should lookup a new lib for react using Hook.
Or build Intersection Observer :)

**Comment by loktar00** [comment]
I agree, I definitely let this slip, got too busy with the day job :/

**Comment by smolak** [comment]
@loktar00 - will you work on Intersection Observer implementation?

**Comment by loktar00** [comment]
@smolak I might as well, was on vacation just got back yesterday.. kind of want to look at the entire component with fresh eyes honestly. It might become a 3.0 with the changes required.

**Comment by nicoandresr** [comment]
I'm still got this error with version `3.1.13`.

**Comment by loktar00** [comment]
This should now be resolved with 4.0.0
