### ISSUE TITLE
Strict Mode compatibility

### ISSUE THREAD

**Issue by gempir** [loktar00/react-lazy-load#145]
It would be great to make this library compatible with react strict mode. 

https://reactjs.org/docs/strict-mode.html

> Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of LazyLoad which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node

**Comment by loktar00** [comment]
Working on this currently, adding the enhancement label.

**Comment by loktar00** [comment]
This should now work with 4.0, fixed in #155
