### ISSUE TITLE
Should use componentDidUpdate instead of componentWillRecieveProps

### ISSUE THREAD

**Issue by NeusFear** [loktar00/react-lazy-load#147]
In newer versions of react this will need to be done, but for now I'm mentioning it because I hate to see Warnings.

> Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 18.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: LazyLoad

**Comment by loktar00** [comment]
No longer an issue as this was removed from the codebase in #155
