### ISSUE TITLE
NPM Installation Error in React@17+

### ISSUE THREAD

**Issue by HeppyAndriawan** [loktar00/react-lazy-load#148]
I've got this error while installing the package and it says:

Could not resolve dependency:
npm ERR! peer react@"^0.14.0 || ^15.0.0-0 || ^16.0.0" from react-lazy-load@3.1.13
npm ERR! node_modules/react-lazy-load
npm ERR!   react-lazy-load@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by ChrisTav424** [comment]
I'm getting the same, be interested to know the outcome

**Comment by Baspa** [comment]
I got the same error. I am on react version `^17.0.2`

**Comment by douglasrcjames** [comment]
Bump, I guess I wont be using this library either lol :/

**Comment by amillward** [comment]
See https://github.com/loktar00/react-lazy-load/pull/146

**Comment by loktar00** [comment]
Should be good to go now, merged the commit, also got rid of a previous error as well. Newest vs is 3.1.14
