### ISSUE TITLE
4.0.0 was published with development dependencies in dependencies

### ISSUE THREAD

**Issue by wopian** [loktar00/react-lazy-load#158]
4.0.0 was released with the following `dependencies`:

```json
{
  "dependencies": {
    "@vitejs/plugin-react": "^2.0.1",
    "typescript": "^4.7.4",
    "vite": "^3.0.9",
    "vite-plugin-dts": "^1.4.1"
  }
}
```

All of these are development dependencies for building the package for publishing, and are not used in the production code - severely bloating `node_modules` for React users who haven't made the switch to Vite yet.

**Comment by loktar00** [comment]
Oh nice catch! I'm actually dealing with a power outage funny enough, tentative power restore is today or tomorrow... so I will get this fixed this weekend at the latest,

I would 100% accept a PR if you're able to do it prior.
