### ISSUE TITLE
Add an optional margin for loading content before it's on screen

### ISSUE THREAD

**Issue by fabiosantoscode** [loktar00/react-lazy-load#16]
This is important because images and iframes take some time to load, and we might want to load them a bit before their time.

Proposed usage:

`<LazyLoad margin={300}>Some content!</LazyLoad>`

**Comment by sergeylaptev** [comment]
I’m not quite sure I follow you. What exactly this margin should do in context of listening scroll event?

**Comment by loktar00** [comment]
I think he means being able to call lazy load before its actually in the view port with an offset value.

**Comment by sergeylaptev** [comment]
Oh, now it makes sense. I can make this in 1-2 days if you aren't planning earlier:)

**Comment by loktar00** [comment]
Feel free! :+1:

**Comment by sergeylaptev** [comment]
@loktar00 @fabiosantoscode Here is some stuff;)

**Comment by sergeylaptev** [comment]
This feature has been implemented in this PR https://github.com/loktar00/react-lazy-load/pull/21

**Comment by fabiosantoscode** [comment]
Cool!
