### ISSUE TITLE
Nothing triggers in Safari.

### ISSUE THREAD

**Issue by ehsanpo** [loktar00/react-lazy-load#166]
We just upgraded four site and change from react-lazyload to react-lazy-load.
Woks fine everywhere beside in Safari Desktop Version 16.5 (18615.2.9.11.4).
only thing rendered in dom is `<div class="LazyLoad"></div>`

is there any work around to trigger is manually like the old forceVisible() in old version?

**Comment by jorrit** [comment]
Is anything logged in the developer console?

**Comment by loktar00** [comment]
Alright @jorrit maybe we do need that PR after all I guess. Admittingly I'm not on Safari/Mac at all so not really a way for me to properly test.

**Comment by ehsanpo** [comment]
we fix our problem, we had issue with a parent component being `overlay:hidden` on long pages, we fixed the isuue by removing `overlay:hidden`.

**Comment by loktar00** [comment]
Nice! Ok so it wasn't an issue with the newest version of Safari that's great to hear!
