### ISSUE TITLE
Test coverage

### ISSUE THREAD

**Issue by sergeylaptev** [loktar00/react-lazy-load#22]
We need to cover the component with some tests.

**Comment by blakedietz** [comment]
How could I help on this one. I'm newer to react, but have used tdd for other js projects. I can setup the test framework and assertion libraries if you want.

**Comment by aliocharyzhkov** [comment]
I've added four tests. Now they all fail. After merging PR #64, they will pass. 

Note there's going to be some merging conflicts in inViewport.js. If you'll need my help to resolve them, please, let me know.
