### ISSUE TITLE
React-dom dependency breaks apps with React before 0.14

### ISSUE THREAD

**Issue by sejoker** [loktar00/react-lazy-load#30]
I would expect a bump of the major version because React-dom dependency is a breaking change. On top of that it would be nice to have some notes regarding React version in the README. Take a look how it's managed in react-redux project: https://github.com/rackt/react-redux.

**Comment by sejoker** [comment]
As a result we have to stick with a specific version in a package.json instead of using: 
´"react-lazy-load": "^1.0.5"´

**Comment by sergeylaptev** [comment]
Hello @sejoker and thanks for your report. I reverted last versions which broke compatibility and pushed all React 0.14 stuff into 2.0.0 version.

**Comment by sejoker** [comment]
@sergeylaptev thanks for quick response, works fine now with 1.0.5 and react 0.13.

**Comment by sergeylaptev** [comment]
You are welcome!
