### ISSUE TITLE
Enable travis-ci

### ISSUE THREAD

**Issue by gavacho** [loktar00/react-lazy-load#32]
If you want to re-enable travis-ci for this repository, I can help with the .travis.yml stuff

**Comment by sergeylaptev** [comment]
Hi, for adding travis support, @loktar00 should add it manually. Because this repo placed on his account. @loktar00 what do you think about it?

**Comment by loktar00** [comment]
@sergeylaptev  I think it's a great idea, and I know it's something you've wanted for a while. I actually start vacation tomorrow for the rest of the year so I should have some time to actually look at this.

**Comment by sergeylaptev** [comment]
@loktar00 Great news, i'm waiting for your investigation about this issue;)

**Comment by sergeylaptev** [comment]
@loktar00 What is your thoughts about it? Is there some progress?

**Comment by loktar00** [comment]
Hey @sergeylaptev sorted of implemented it the other day.. need to get it setup properly it seems.

**Comment by sergeylaptev** [comment]
@loktar00 ;)
