### ISSUE TITLE
Feature Request: Add prop for calling a method when in view

### ISSUE THREAD

**Issue by reintroducing** [loktar00/react-lazy-load#33]
Hello and thanks for the great component.

I'd like to request a feature where you can pass a prop to react-lazy-load that is a function to call when the lazy load kicks in and the item comes into view.  What do you think about this?

**Comment by reintroducing** [comment]
I actually created a PR to add this, pretty simple :)

**Comment by sergeylaptev** [comment]
Check my comments in PR, and after fixes I'll accept your request;)
