### ISSUE TITLE
Performance is extremely bad

### ISSUE THREAD

**Issue by gavacho** [loktar00/react-lazy-load#36]
When many instances of this component are on the page, the page becomes noticeably less performant.  Performance could be made better by (1) limiting the number of scroll/resize event handlers are attached to `window` to just 1 and (2) throttling the event handler so that it's only executed once per time interval (250ms is a good place to start).

**Comment by nweinstein7** [comment]
For me, scrolling quickly past a LazyLoad module with an onContentVisible callback results in:

```
Uncaught RangeError: Maximum call stack size exceeded
```

I think it can't handle calling that function so many times so quickly. For instance, when I put a breakpoint in the function and scrolled, it got called a bunch of times. The page also appears to slow down.

Not sure if I'm doing something wrong implementation wise, or if something needs to be fixed.

**Comment by nweinstein7** [comment]
Well I fixed my problem by putting an if statement before any heavy logic to prevent it from doing too much on each scroll... Oddly enough, after adding this if statement (and changing nothing else?), it also seemed to be calling the callback less frequently.... Not sure how that happened.

**Comment by sergeylaptev** [comment]
@gavacho Can you test version 3.0.0, is there some performance improvements for you?
