### ISSUE TITLE
Warning: React.createElement: type should not be null

### ISSUE THREAD

**Issue by zoul** [loktar00/react-lazy-load#40]
I have a very simple component that uses `LazyLoad` a bit like this:

```
var LazyLoad = require('react-lazy-load')
var View = React.createClass({
    render: function() {
        return (
            <LazyLoad>
                <img src={…}/>
            </LazyLoad>
        )
})
```

But when displayed by browser, I get this error in the console:

```
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `View`.
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `View`.
```

What am I doing wrong? I am using 2.0.2 on Node 5.4.1.

**Comment by sergeylaptev** [comment]
Hello, @zoul. Try to require it as `var LazyLoad = require('react-lazy-load').default`;

**Comment by zoul** [comment]
Perfect, that was it! Thank you for the quick reply.

**Comment by sergeylaptev** [comment]
This is an issue of babel 6.0, I'll rollback on plain old module.exports until they fix it. You can use require('react-lazy-load') without `default` when next release will be available.

**Comment by zoul** [comment]
Great!

**Comment by loktar00** [comment]
Maybe I should have waited on jumping to babel 6 :/ heh things like this are why we haven't at work.
