### ISSUE TITLE
Apply lazyload on state change as well

### ISSUE THREAD

**Issue by oncletom** [loktar00/react-lazy-load#42]
Hi :-)

Thanks a lot for your plugin. I use it to wrap images and it works very well on scroll.
Although, I have a list of content within a faceted search page and face an issue here.

When a facet is clicked, the content list gets filtered and some elements which meant to be outside of the viewport become above the fold *but* the lazyload is not triggered. For a good reason: scroll has not happened nor a window resize.

Do you think of another mechanism to trigger a lazyload in case of state change?

Thanks :-)

Here is a demo:

1. scrolling works fine
1. click on a filter
1. nothing happens
1. pictures appear after a brief moment after scroll

![freebird-lazyload](https://cloud.githubusercontent.com/assets/138627/12751589/de84da88-c9b5-11e5-9882-113d3ff301db.gif)

**Comment by sergeylaptev** [comment]
@oncletom Hello. I understood your problem. Probably we can listen component update event and recalculate visibility state. Need to investigate this feature and possible performance issues (for now we update lazyload component only once when its state is visible). I'll check this on the weekend. Do you have any suggestions?

**Comment by oncletom** [comment]
@sergeylaptev yes I guess a single call to `shouldComponentUpdate` is needed, the rest of them should be debounced as currently done for scroll and resize events. If you give me a hint at where to tackle I can eventually propose a PR tomorrow.

**Comment by sergeylaptev** [comment]
@oncletom Probably will be enough to remove shouldComponent update in LazyLoad and re-execute lazyLoadHandler in componentWillReceiveProps. lazyLoadHandler is debounced and calculation will be processed in 250ms (by default).

**Comment by sergeylaptev** [comment]
@oncletom Can you show me code example with this issue? Probably, you use indexed keys for lazy loadable items, and when you navigate to another page, components just updated instead of unmounting (even if content is another). You should use key with unique ids.

**Comment by loktar00** [comment]
Weird issue I bet @sergeylaptev  is right about the key updates. However are you 100% sure the images are loaded as well already? In your example when it takes them a second to load it's almost as if the resources themselves just aren't ready yet.

**Comment by steevel** [comment]
I have the same problem as OP, it's a product listing and while using a facet to filter products from the bottom of the list aren't displayed when coming to the top. This worked in 2.x so I just reverted my upgrade to 3.x. There might be a problem with my markup since <LazyLoad> is not my top element in the loop, thus it doesn't have the "key" attribute (the top element does).

I don't have time to investigate at the moment but I wanted to let you know that I experience this too!

**Comment by sergeylaptev** [comment]
@steevel Can you provide code example which reproduces this unexpected behaviour?

**Comment by edouarobin** [comment]
@oncletom  To force recalculate the visibility state, this hack works pretty well:
````
window.scrollBy(0, 1);
window.scrollBy(0, -1);
````
