### ISSUE TITLE
Add onContentNotVisibleAnymore (or something like that)

### ISSUE THREAD

**Issue by qsomazzi** [loktar00/react-lazy-load#45]
Hello,

I'm using your react component and for my use-case I miss a simple feature,
I want to call a function when an element was visible, but not anymore.

I'm using your stuff for a news reader, when i scroll to read a news, and I arrive to the bottom of it, (means I've read it) I want to call a function to set it as Read.

What do you think about this feature ?

Thanks

**Comment by sergeylaptev** [comment]
Hi. I'm not sure that fully understood your problem. How lazy load component related with marking news list as read? Is it grid of news tiles? Probably you want feature which can be described as: "Notify me by triggering my callback, when you (lazy loadable content) will be outside the viewport for the first time". Am I right?

**Comment by qsomazzi** [comment]
Yeah exactly ! I'm sorry it's quite hard to explain myself clearly in english :p

**Comment by sergeylaptev** [comment]
I'll investigate this issue at this weekend.

**Comment by qsomazzi** [comment]
Awesome ! Thanks

**Comment by qsomazzi** [comment]
Hi ! any update on this ?

**Comment by sergeylaptev** [comment]
Sorry, I still have no time for this. Hopefully implement in a couple days

**Comment by qsomazzi** [comment]
Don't worry, just checking :) take your time, it's awesome you agree to do this so not in hurry at all :)

**Comment by sejoker** [comment]
I think it feasible to implement but IMO it is out of the scope for the particular component. The main purpose of it to load some resources in deferred mode (e.g. images), as soon as the component came into viewport all the event handlers are unregistered. Adding `onContentNotVisibleAnymore` will require postponing unregistration of event handlers till later stage which is undesirable for the general use case.

**Comment by qsomazzi** [comment]
Hi @sejoker, thanks for your answer but maybe there is a way to configure it to enable it only on demand to avoid undesirable stuff for general use case and provide a cool new feature for other case ?

**Comment by sejoker** [comment]
@qsomazzi of course, it possible, but IMO first we need to have good code coverage https://github.com/loktar00/react-lazy-load/issues/22

**Comment by qsomazzi** [comment]
Okay, I understand. For the moment I've use the combo with this lib and https://github.com/brigade/react-waypoint do manage my case so it's ok :)
