### ISSUE TITLE
Listen for animationend event

### ISSUE THREAD

**Issue by sejoker** [loktar00/react-lazy-load#48]
I am testing the 3rd version of the component. Our carousel component has a number of slides which loaded immediately in 2nd version when entered into viewport. 

![furnishings the art of furniture from 16th to 20th century auction auctionata](https://cloud.githubusercontent.com/assets/125466/14143027/467d972e-f689-11e5-90e2-2f1cbd6a95ab.png)

But with 3rd version the logic of lazy component loads only images which are visible so when we click on next slide button the images are not loaded until we start scrolling.

![furnishings the art of furniture from 16th to 20th century auction auctionata 2](https://cloud.githubusercontent.com/assets/125466/14143086/9f0b0fb6-f689-11e5-88a7-f5d000a35517.png)

There multiple approaches to handle the issue. One would be listening on animation events, another to expose a callback we could call to trigger loading logic evaluation.

What would be the suggested approach in my case?

**Comment by sergeylaptev** [comment]
@sejoker If you suggest to implement animationEnd behaviour, than probably you assume that images can be shown after this type of event. In this case you can listen animationEnd event and render LazyLoad component when it's fired. LazyLoad will check whether component in viewport and it will.

**Comment by sejoker** [comment]
@sergeylaptev thanks for prompt reply. I agree, animationEnd is too specific to bring into LazyLoad itself. What would be the quickest way to have previous behaviour for the component: load all images when component come into viewport?

**Comment by sejoker** [comment]
I mean it's quite a breaking change from version 2, it would be great to have a migration path in Readme.

**Comment by sergeylaptev** [comment]
@sejoker How these images can be in viewport, if they are outside of it? Especially for horizontal slider. Maybe they have opacity 0?

**Comment by sejoker** [comment]
I guess there was some bug in the logic of isInViewport which was fixed in version 3 :) As for you question we use CSS translate3d styles to switch between slides. I am going to close the ticket.
