### ISSUE TITLE
Dynamic loading of images results in blank images until scroll

### ISSUE THREAD

**Issue by yaksandpie** [loktar00/react-lazy-load#60]
When additional images are put on the page dynamically, the new images that are visible in the viewport are not loaded until a scroll event happens. 

It would be nice to be able to trigger the "check for images in viewport" functionality manually.

**Comment by sergeylaptev** [comment]
This check is already exists https://github.com/loktar00/react-lazy-load/blob/master/src/LazyLoad.jsx#L43-L45
