### ISSUE TITLE
Uncaught Error: getNodeFromInstance: Invalid argument.

### ISSUE THREAD

**Issue by pixelatorz** [loktar00/react-lazy-load#69]
I am using LazyLoad 3.0.10 in combination with react 15.2.0 amd react-dom 15.2.1

when openening the compontent the following error gets thrown:
**Uncaught Error: getNodeFromInstance: Invalid argument.**

![screen shot 2016-08-17 at 16 05 35](https://cloud.githubusercontent.com/assets/1567481/17739181/8b7f015e-6494-11e6-9139-db22fa53d5c2.png)

this is a fragment of the code:

```
import LazyLoad from 'react-lazy-load';
import React from 'react';

    getGameMedia()
    {
        return(
            <div className="games_list_item_game_media">
                <LazyLoad height={300} offsetTop={200}>
                    <img src={this.props.data.tutorialThumbnail} className="width100" alt="" />
                </LazyLoad>
            </div>
        );
    }
```

**Comment by loktar00** [comment]
Won't be fixing this as I'm focusing on 17 and 18 only now.
