### ISSUE TITLE
Avoid wrapper?

### ISSUE THREAD

**Issue by NeXTs** [loktar00/react-lazy-load#74]
Do we really need [this wrapper](https://github.com/loktar00/react-lazy-load/blob/master/src/LazyLoad.jsx#L115)?
It breaks style-specific items on my list and I don't want to override those styles to lazy-loader's wrapper :\

Why don't just render actual child node, as [react-lazyload does](https://github.com/jasonslyvia/react-lazyload/blob/master/src/index.js#L240)?

**Comment by wzup** [comment]
@NeXTs  react-lazyload doesn't work BTW. But this plugin works just fine
