### ISSUE TITLE
findDOMNode called on an unmounted component

### ISSUE THREAD

**Issue by nickpalmer** [loktar00/react-lazy-load#83]
I have integrated react-lazy-load, however, I am seeing the following problem when switching routes in our app.

Uncaught Error: findDOMNode was called on an unmounted component.
    at invariant (invariant.js:38)
    at findDOMNode (findDOMNode.js:52)
    at LazyLoad.lazyLoadHandler (LazyLoad.js:121)
    at invokeFunc (index.js:160)
    at trailingEdge (index.js:207)
    at timerExpired (index.js:195)
    at _super.buglog (buglog.js:82)

LazyLoad.js:121 is the first call to findDOMNode in the handler function. In debugging this I am seeing cancel() being called on the handler and the events being unregistered however, it is still being called.

```npm ls``` tells me:

├─┬ react-lazy-load@3.0.10
│ ├── eventlistener@0.0.1
│ └── lodash.debounce@4.0.8

**Comment by jonathanobino** [comment]
I've solved this in my version of react [lazy loading components](https://github.com/jonathanobino/react-lazy)
