### ISSUE TITLE
ES6 breaks existing imports

### ISSUE THREAD

**Issue by grassick** [loktar00/react-lazy-load#86]
I used to be able to do this:

`LazyLoad = require('react-lazy-load')`

but now need to do this:

`LazyLoad = require('react-lazy-load').default`

in Webpack + Javascript. Perhaps a warning in the README?

**Comment by bf** [comment]
Yes this breaks antd for me!

**Comment by loktar00** [comment]
Should be resolved with the newest version, will address if not however definitely recommending using ES modules.
