### ISSUE TITLE
Whats Happen With This Basic Example

### ISSUE THREAD

**Issue by prakasa1904** [loktar00/react-lazy-load#87]
Just want to show here, LOL.... Coz I really don't know how to fix this error in basic code.

Here my screen shoot : http://imgur.com/a/1I9jg

**Comment by surinderdemo** [comment]
Something else is being hosted on your localhost:3000 port.

**Comment by Vasikaran** [comment]
I receive the same error when I start the server by using npm start.

**Comment by loktar00** [comment]
This is fixed in the branch I'm working on, the example has been greatly reduced in complexity for hosting.
