### ISSUE TITLE
Make it possible to lazy load floating elements

### ISSUE THREAD

**Issue by jwamsterdam** [loktar00/react-lazy-load#88]
Hi, 

Are you able to adapt the code of your package so it works with floating elements?
currently, this doesn't work.

Many thanks!

**Comment by mherodev** [comment]
Flex elements in a horizontal scroller also do not load correctly.

**Comment by mherodev** [comment]
Scratch that, they're working as far as I can tell. I imagine I was testing this inside Chrome's device toolbar when I first commented on this issue. See #105
