### ISSUE TITLE
Error in your basic example.

### ISSUE THREAD

**Issue by Vasikaran** [loktar00/react-lazy-load#93]
I can't run your basic example. When I try to start the server, suddenly throw the **Cannot find module babel-core/register** error displayed.

**Comment by danbrellis** [comment]
I also get this error. Any suggestions?

**Comment by gl0gl0** [comment]
I'm having the same error as well

**Comment by cokafor571** [comment]
Me as well, I will mess around with the setup and see if I can get it to work

**Comment by willymai** [comment]
just remove single quotes in package.json
May it help you guys ✌️

**Comment by loktar00** [comment]
Newest version being worked on fortunately solves the issues with the example.
