### ISSUE TITLE
Feature request: Low Quality Image Placeholders (LQIP)

### ISSUE THREAD

**Issue by stereobooster** [loktar00/react-lazy-load#95]
Description of techinque https://jmperezperez.com/medium-image-progressive-loading-placeholder/

Related:
 - https://github.com/aFarkas/lazysizes
 - https://blog.imgix.com/2016/06/01/lqip-your-images.html
 - https://github.com/zouhir/lqip-loader

**Comment by tstirrat15** [comment]
Would this allow for the designation of a LQIP through a `placeholder` prop as you see it? Or would it be something where it's automatically doing something with the image to the image?

**Comment by stereobooster** [comment]
No you need to provide low quality placeholder as base64 encoded string as property. While image not loaded component will show LQIP (`background-size: cover`) as soon image get loaded it will be over background.
